package lean4worker

import (
	"encoding/json"
	"fmt"
	"regexp"
	"slices"
	"strings"
)

var upperAtomPattern = regexp.MustCompile(`\b[A-Z][A-Za-z0-9_]*\b`)

func DecodeModulePayload(raw []byte) (ModulePayload, error) {
	if len(strings.TrimSpace(string(raw))) == 0 {
		return ModulePayload{}, nil
	}
	var payload ModulePayload
	if err := json.Unmarshal(raw, &payload); err != nil {
		return ModulePayload{}, fmt.Errorf("decode lean payload: %w", err)
	}
	return payload, nil
}

func RenderModule(job Job) (string, error) {
	name := strings.TrimSpace(job.Name)
	statement := strings.TrimSpace(job.Statement)
	if name == "" {
		return "", fmt.Errorf("lean job name is required")
	}
	if statement == "" {
		return "", fmt.Errorf("lean job statement is required")
	}

	payload, err := DecodeModulePayload(job.Payload)
	if err != nil {
		return "", err
	}

	imports := uniqueLeanImports(append([]string{"Mathlib.Tactic"}, payload.Imports...))
	theoremName := sanitizeLeanIdentifier(name)
	autoVars := extractUpperAtoms(statement)

	var b strings.Builder
	for _, imp := range imports {
		b.WriteString("import ")
		b.WriteString(strings.TrimSpace(imp))
		b.WriteByte('\n')
	}
	b.WriteString("\nnamespace CollabSphereLean.Generated\n\n")
	b.WriteString("/- Generated by CollabSphere Go orchestration. -/\n\n")

	if len(autoVars) > 0 {
		b.WriteString("variable {")
		b.WriteString(strings.Join(autoVars, " "))
		b.WriteString(" : Prop}\n\n")
	}

	for _, helper := range payload.Helpers {
		helper = strings.TrimSpace(helper)
		if helper == "" {
			continue
		}
		b.WriteString(helper)
		b.WriteString("\n\n")
	}

	b.WriteString("theorem ")
	b.WriteString(theoremName)
	b.WriteString(" : ")
	b.WriteString(statement)
	b.WriteString(" := by\n")
	proof := strings.TrimSpace(payload.Proof)
	if proof == "" {
		b.WriteString("  exact ?_\n")
	} else {
		for _, line := range strings.Split(proof, "\n") {
			if strings.TrimSpace(line) == "" {
				b.WriteByte('\n')
				continue
			}
			b.WriteString("  ")
			b.WriteString(line)
			b.WriteByte('\n')
		}
	}
	b.WriteString("\nend CollabSphereLean.Generated\n")
	return b.String(), nil
}

func uniqueLeanImports(imports []string) []string {
	seen := make(map[string]struct{}, len(imports))
	result := make([]string, 0, len(imports))
	for _, imp := range imports {
		imp = strings.TrimSpace(imp)
		if imp == "" {
			continue
		}
		if _, ok := seen[imp]; ok {
			continue
		}
		seen[imp] = struct{}{}
		result = append(result, imp)
	}
	return result
}

func sanitizeLeanIdentifier(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "GeneratedJob"
	}
	var b strings.Builder
	for i, r := range value {
		valid := (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r == '_' || (i > 0 && r >= '0' && r <= '9')
		if valid {
			b.WriteRune(r)
			continue
		}
		if b.Len() == 0 || b.String()[b.Len()-1] == '_' {
			continue
		}
		b.WriteByte('_')
	}
	result := strings.Trim(b.String(), "_")
	if result == "" {
		return "GeneratedJob"
	}
	first := result[0]
	if first >= '0' && first <= '9' {
		return "J_" + result
	}
	return result
}

func extractUpperAtoms(statement string) []string {
	matches := upperAtomPattern.FindAllString(statement, -1)
	if len(matches) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(matches))
	result := make([]string, 0, len(matches))
	for _, match := range matches {
		if _, ok := seen[match]; ok {
			continue
		}
		seen[match] = struct{}{}
		result = append(result, match)
	}
	slices.Sort(result)
	return result
}
