package report

import (
	"context"
	"encoding/csv"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/NikolayNam/collabsphere/platform-tooling/internal/research/planner"
	"github.com/NikolayNam/collabsphere/platform-tooling/internal/toolingpath"
)

func EnsureModelCatalog(path string, jobs []planner.BenchmarkJob) error {
	if strings.TrimSpace(path) == "" {
		return fmt.Errorf("benchmark model catalog path is required")
	}
	if _, err := os.Stat(path); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat benchmark model catalog %s: %w", path, err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create benchmark model catalog dir: %w", err)
	}
	unique := map[string]struct{}{}
	models := make([]string, 0, len(jobs))
	for _, job := range jobs {
		model := strings.TrimSpace(job.Model)
		if model == "" {
			continue
		}
		if _, ok := unique[model]; ok {
			continue
		}
		unique[model] = struct{}{}
		models = append(models, model)
	}
	sort.Strings(models)

	file, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create benchmark model catalog %s: %w", path, err)
	}
	defer file.Close()

	writer := csv.NewWriter(file)
	defer writer.Flush()
	if err := writer.Write([]string{"llm_model", "display_name", "size_bucket", "size_label", "tier", "comparison_status", "notes"}); err != nil {
		return fmt.Errorf("write benchmark model catalog header: %w", err)
	}
	for _, model := range models {
		if err := writer.Write([]string{model, model, "unknown", "n/a", "research", "unclassified", "generated by researchctl"}); err != nil {
			return fmt.Errorf("write benchmark model catalog row %q: %w", model, err)
		}
	}
	writer.Flush()
	if err := writer.Error(); err != nil {
		return fmt.Errorf("flush benchmark model catalog %s: %w", path, err)
	}
	return nil
}

func GenerateBenchmarkReport(ctx context.Context, workspaceRoot, projectFolder, inputFile, summaryPath, modelCatalogPath, reportOut string) error {
	return runContractsCommand(ctx, workspaceRoot, "hilbert-benchmark-report",
		"-project-folder", projectFolder,
		"-cases-file", inputFile,
		"-summary", summaryPath,
		"-model-catalog", modelCatalogPath,
		"-out", reportOut,
	)
}

func GenerateResearchReport(ctx context.Context, workspaceRoot, projectFolder, inputFile string, summaryPaths []string, modelCatalogPath, reportOut string) error {
	return runContractsCommand(ctx, workspaceRoot, "hilbert-benchmark-research-report",
		"-project-folder", projectFolder,
		"-cases-file", inputFile,
		"-summary", strings.Join(summaryPaths, ","),
		"-model-catalog", modelCatalogPath,
		"-out", reportOut,
	)
}

func GenerateMetaReport(ctx context.Context, workspaceRoot, projectFolder, inputFile string, summaryPaths []string, modelCatalogPath, reportOut string) error {
	return runContractsCommand(ctx, workspaceRoot, "hilbert-benchmark-meta-report",
		"-project-folder", projectFolder,
		"-cases-file", inputFile,
		"-summary", strings.Join(summaryPaths, ","),
		"-model-catalog", modelCatalogPath,
		"-out", reportOut,
	)
}

func GenerateCaseReport(ctx context.Context, workspaceRoot, projectFolder, inputFile string, summaryPaths []string, reportOut string) error {
	return runContractsCommand(ctx, workspaceRoot, "hilbert-benchmark-case-report",
		"-project-folder", projectFolder,
		"-cases-file", inputFile,
		"-summary", strings.Join(summaryPaths, ","),
		"-out", reportOut,
	)
}

func runContractsCommand(ctx context.Context, workspaceRoot, subcommand string, args ...string) error {
	goBinary, err := exec.LookPath("go")
	if err != nil {
		return fmt.Errorf("locate go binary: %w", err)
	}
	toolingRoot := filepath.Join(workspaceRoot, "platform-tooling")
	commandArgs := append([]string{"-C", toolingRoot, "run", "./cmd/contracts", subcommand}, args...)
	cmd := exec.CommandContext(ctx, goBinary, commandArgs...)
	cmd.Env = append(os.Environ(), fmt.Sprintf("%s=%s", toolingpath.WorkspaceRootEnvKey, workspaceRoot))
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("run contracts %s: %w\n%s", subcommand, err, strings.TrimSpace(string(output)))
	}
	return nil
}
